version: "3"

services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    depends_on:
      - ncdb
    ports:
      - 80:80
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_ROOT_PASSWORD=nextcloud
    volumes:
      - nextcloud:/var/www/html

  ncdb:
    image: mariadb
    container_name: db
    #command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    command: --innodb-read-only-compressed=OFF
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_ROOT_PASSWORD=nextcloud
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
  nextcloud:
